/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'haroldev' at '19/05/17 13:24' with Gradle 2.14.1
 *
 * @author haroldev, @date 19/05/17 13:24
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
